version: '3.7'
services:
  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    volumes:
      - prometheus-linux-data:/prometheus
      - ./config:/etc/prometheus
    ports:
      - 9090:9090
    networks:
      - prometheus-linux

  grafana:
    container_name: grafana
    image: grafana/grafana
    volumes:
      -  grafana-linux-data:/var/lib/grafana
      - ./config/grafana/:/etc/grafana/provisioning/
    ports:
      - 3000:3000
    depends_on:
      - prometheus
    networks:
      - prometheus-linux

volumes:
  prometheus-linux-data:
  grafana-linux-data:

networks: 
  prometheus-windows-linux: