global:
  scrape_interval: 15s
  
scrape_configs:
  - job_name: 'windows_exporter' #Informações ambiente windows
    scrape_interval: 5s
    static_configs:
      - targets: ['host.docker.internal:9182']
        